"""
Generate comprehensive 182-species registry and label_map.json for Ornitho-Ex.
"""

from __future__ import annotations
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC  = os.path.join(ROOT, "src")
if SRC not in sys.path:
    sys.path.insert(0, SRC)

from inference.species_names import _SPECIES_DB

additional = {
    "Accipiter gentilis": {
        "common": "Northern Goshawk",
        "emoji": "🦅",
        "habitat": "Dense conifer & mixed forest",
        "description": "Fierce apex raptor of mature old-growth woodland.",
        "color": "#7dd3fc",
    },
    "Accipiter nisus": {
        "common": "Eurasian Sparrowhawk",
        "emoji": "🦅",
        "habitat": "Woodland, gardens & farmland",
        "description": "Agile raptor hunting songbirds through forest clearings.",
        "color": "#94a3b8",
    },
    "Acrocephalus schoenobaenus": {
        "common": "Sedge Warbler",
        "emoji": "🌾",
        "habitat": "Reedbeds & wet ditches",
        "description": "Lively, improvisational singer from marshes with rapid bursts.",
        "color": "#86efac",
    },
    "Aegithalos caudatus": {
        "common": "Long-tailed Tit",
        "emoji": "🍡",
        "habitat": "Hedgerows & deciduous scrub",
        "description": "Tiny fluffy ball with disproportionately long tail, moves in flocks.",
        "color": "#fbcfe8",
    },
    "Aegolius funereus": {
        "common": "Boreal Owl",
        "emoji": "🦉",
        "habitat": "Taiga & mountain spruce forests",
        "description": "Small nocturnal owl of northern boreal forests with bell-like calls.",
        "color": "#c4b5fd",
    },
    "Anas crecca": {
        "common": "Eurasian Teal",
        "emoji": "🦆",
        "habitat": "Shallow wetlands & marshes",
        "description": "Smallest European dabbling duck with a piping whistle.",
        "color": "#7dd3fc",
    },
    "Anas platyrhynchos": {
        "common": "Mallard",
        "emoji": "🦆",
        "habitat": "Ponds, lakes & rivers",
        "description": "Familiar iridescent green-headed wild duck.",
        "color": "#86efac",
    },
    "Anser anser": {
        "common": "Greylag Goose",
        "emoji": "🪿",
        "habitat": "Lakes, estuaries & grazing marshes",
        "description": "Ancestor of domestic geese with resonant honking calls.",
        "color": "#fed7aa",
    },
    "Anthus cervinus": {
        "common": "Red-throated Pipit",
        "emoji": "🌿",
        "habitat": "Tundra & damp coastal marshes",
        "description": "Subtle pinkish throat in breeding plumage, high shrill calls.",
        "color": "#fef08a",
    },
    "Aquila chrysaetos": {
        "common": "Golden Eagle",
        "emoji": "👑",
        "habitat": "Mountain crags & moorland",
        "description": "Majestic apex predator soaring over remote highland ridges.",
        "color": "#fed7aa",
    },
    "Ardea cinerea": {
        "common": "Grey Heron",
        "emoji": "🪶",
        "habitat": "Rivers, lakes & tidal mudflats",
        "description": "Statuesque wading bird stalking fish with lightning strikes.",
        "color": "#94a3b8",
    },
    "Asio otus": {
        "common": "Long-eared Owl",
        "emoji": "🦉",
        "habitat": "Conifer belts near open fields",
        "description": "Secretive nocturnal owl with prominent head tufts and orange eyes.",
        "color": "#fed7aa",
    },
    "Athene noctua": {
        "common": "Little Owl",
        "emoji": "🦉",
        "habitat": "Orchards, old farmland & stone walls",
        "description": "Compact daylight-active owl with piercing yellow eyes.",
        "color": "#fef08a",
    },
    "Aythya fuligula": {
        "common": "Tufted Duck",
        "emoji": "🦆",
        "habitat": "Reservoirs, lakes & park waters",
        "description": "Diving duck with bold white flank patches and drooping crest.",
        "color": "#7dd3fc",
    },
    "Bombycilla garrulus": {
        "common": "Bohemian Waxwing",
        "emoji": "🍒",
        "habitat": "Boreal forests & berry trees",
        "description": "Crested winter visitor famous for sleek plumage and trilling calls.",
        "color": "#fbcfe8",
    },
    "Botaurus stellaris": {
        "common": "Eurasian Bittern",
        "emoji": "🎋",
        "habitat": "Dense reedbeds",
        "description": "Master of camouflage producing a deep resonant foghorn boom.",
        "color": "#fed7aa",
    },
    "Bubo bubo": {
        "common": "Eurasian Eagle-Owl",
        "emoji": "🦉",
        "habitat": "Rocky cliffs & wooded valleys",
        "description": "One of the largest owls in the world with deep booming hoot.",
        "color": "#fed7aa",
    },
    "Buteo lagopus": {
        "common": "Rough-legged Buzzard",
        "emoji": "🦅",
        "habitat": "Arctic tundra & open winter plains",
        "description": "Hovering northern raptor with feathered legs and pale tail.",
        "color": "#94a3b8",
    },
    "Calcarius lapponicus": {
        "common": "Lapland Longspur",
        "emoji": "❄️",
        "habitat": "Arctic tundra & coastal saltmarshes",
        "description": "Hardy northern songbird with chestnut nape and musical flight call.",
        "color": "#fef08a",
    },
    "Calidris alpina": {
        "common": "Dunlin",
        "emoji": "🌊",
        "habitat": "Coastal mudflats & peat bogs",
        "description": "Small shorebird flocking in synchronised waves along tides.",
        "color": "#7dd3fc",
    },
    "Carduelis flammea": {
        "common": "Common Redpoll",
        "emoji": "🍓",
        "habitat": "Birch scrub & boreal woodland",
        "description": "Acrobatic finch with crimson forehead foraging on birch seeds.",
        "color": "#fbcfe8",
    },
    "Carpodacus erythrinus": {
        "common": "Common Rosefinch",
        "emoji": "🌸",
        "habitat": "River valleys & willow thickets",
        "description": "Crimson-red male singing a sweet flute-like song.",
        "color": "#fbcfe8",
    },
    "Charadrius dubius": {
        "common": "Little Ringed Plover",
        "emoji": "🏖️",
        "habitat": "Gravel pits & shingle riverbeds",
        "description": "Active shorebird with distinctive golden eye-ring.",
        "color": "#fef08a",
    },
    "Charadrius hiaticula": {
        "common": "Common Ringed Plover",
        "emoji": "🏖️",
        "habitat": "Sandy & pebble beaches",
        "description": "Bold black-and-white neck collar and piping melodic call.",
        "color": "#fed7aa",
    },
    "Chlidonias niger": {
        "common": "Black Tern",
        "emoji": "🪶",
        "habitat": "Inland marshes & shallow fens",
        "description": "Graceful marsh tern dipping to pluck insects from water.",
        "color": "#7dd3fc",
    },
    "Cinclus cinclus": {
        "common": "White-throated Dipper",
        "emoji": "🌊",
        "habitat": "Fast-flowing rocky streams",
        "description": "Songbird that walks underwater along riverbeds for nymphs.",
        "color": "#94a3b8",
    },
    "Circus aeruginosus": {
        "common": "Western Marsh Harrier",
        "emoji": "🌾",
        "habitat": "Expansive reedbeds & fens",
        "description": "Broad-winged harrier quartering low over reedbeds on V-shaped wings.",
        "color": "#fed7aa",
    },
    "Circus cyaneus": {
        "common": "Hen Harrier",
        "emoji": "🦅",
        "habitat": "Heather moorland & open marsh",
        "description": "Ghost-grey male performing tumbling courtship sky-dances.",
        "color": "#94a3b8",
    },
    "Clangula hyemalis": {
        "common": "Long-tailed Duck",
        "emoji": "❄️",
        "habitat": "Arctic tundra lakes & coastal seas",
        "description": "Deep-diving sea duck with musical yodelling call.",
        "color": "#7dd3fc",
    },
    "Columba oenas": {
        "common": "Stock Dove",
        "emoji": "🕊️",
        "habitat": "Old woodland & parkland",
        "description": "Fast-flying wild pigeon with iridescent green neck patch.",
        "color": "#c4b5fd",
    },
    "Coracias garrulus": {
        "common": "European Roller",
        "emoji": "💎",
        "habitat": "Warm open lowland & oak savannah",
        "description": "Brilliant turquoise bird of prey doing aerobatic rolling displays.",
        "color": "#7dd3fc",
    },
    "Corvus corax": {
        "common": "Northern Raven",
        "emoji": "🖤",
        "habitat": "Mountains, sea cliffs & deep forest",
        "description": "Massive intelligent corvid with deep cronking call and diamond tail.",
        "color": "#94a3b8",
    },
    "Corvus frugilegus": {
        "common": "Rook",
        "emoji": "🌳",
        "habitat": "Farmland & communal rookeries",
        "description": "Sociable corvid with bare greyish-white bill base.",
        "color": "#94a3b8",
    },
    "Corvus monedula": {
        "common": "Western Jackdaw",
        "emoji": "👀",
        "habitat": "Old buildings, cliffs & farmland",
        "description": "Compact corvid with silvery nape and piercing pale eyes.",
        "color": "#94a3b8",
    },
    "Coturnix coturnix": {
        "common": "Common Quail",
        "emoji": "🌾",
        "habitat": "Cereal fields & dry grassland",
        "description": "Secretive ground-dwelling gamebird with rhythmic piping call.",
        "color": "#fed7aa",
    },
    "Crex crex": {
        "common": "Corn Crake",
        "emoji": "🌾",
        "habitat": "Hay meadows & tall herb fields",
        "description": "Nocturnal rasping call across traditional hay meadows.",
        "color": "#fed7aa",
    },
    "Cyanistes caeruleus": {
        "common": "Eurasian Blue Tit",
        "emoji": "💙",
        "habitat": "Deciduous woods & garden feeders",
        "description": "Energetic garden tit with bright cobalt cap and yellow chest.",
        "color": "#7dd3fc",
    },
    "Cygnus cygnus": {
        "common": "Whooper Swan",
        "emoji": "🪿",
        "habitat": "Remote taiga bogs & open floodlands",
        "description": "Large wild swan with lemon-yellow wedge on bill and bugling call.",
        "color": "#fef08a",
    },
    "Cygnus olor": {
        "common": "Mute Swan",
        "emoji": "🦢",
        "habitat": "Lowland lakes, canals & rivers",
        "description": "Graceful classic swan with orange bill and black basal knob.",
        "color": "#f8fafc",
    },
    "Dendrocopos minor": {
        "common": "Lesser Spotted Woodpecker",
        "emoji": "🪵",
        "habitat": "Deciduous woodland canopies & orchards",
        "description": "Sparrow-sized woodpecker foraging in high rotten twigs.",
        "color": "#fbcfe8",
    },
    "Emberiza calandra": {
        "common": "Corn Bunting",
        "emoji": "🌾",
        "habitat": "Arable farmland & open plains",
        "description": "Chunky bunting singing a jingling keys song from fence posts.",
        "color": "#fed7aa",
    },
    "Emberiza cirlus": {
        "common": "Cirl Bunting",
        "emoji": "🌱",
        "habitat": "Sunlit hillsides, hedges & vineyards",
        "description": "Striking black-and-yellow facial pattern with buzzing trill.",
        "color": "#fef08a",
    },
    "Emberiza hortulana": {
        "common": "Ortolan Bunting",
        "emoji": "🌾",
        "habitat": "Dry farmland with scattered trees",
        "description": "Olive-grey head, pink bill, and sweet melancholic cadence.",
        "color": "#fed7aa",
    },
    "Eremophila alpestris": {
        "common": "Horned Lark",
        "emoji": "🏔️",
        "habitat": "Alpine meadows & arctic tundra",
        "description": "Yellow face mask with tiny black feather horns.",
        "color": "#fef08a",
    },
    "Falco columbarius": {
        "common": "Merlin",
        "emoji": "🦅",
        "habitat": "Open moorland & coastal marshes",
        "description": "Europe's smallest falcon, fast and low-flying hunter.",
        "color": "#94a3b8",
    },
    "Falco peregrinus": {
        "common": "Peregrine Falcon",
        "emoji": "⚡",
        "habitat": "High sea cliffs & gorge crags",
        "description": "Fastest animal on Earth, stooping at over 300 km/h.",
        "color": "#7dd3fc",
    },
    "Falco subbuteo": {
        "common": "Eurasian Hobby",
        "emoji": "🦅",
        "habitat": "Heathland & open woodland edges",
        "description": "Sleek falcon catching dragonflies and swifts in mid-air.",
        "color": "#c4b5fd",
    },
    "Falco tinnunculus": {
        "common": "Common Kestrel",
        "emoji": "🦅",
        "habitat": "Roadside verges, farmland & coasts",
        "description": "Iconic raptor hovering stationary in wind hunting voles.",
        "color": "#fed7aa",
    },
    "Ficedula albicollis": {
        "common": "Collared Flycatcher",
        "emoji": "🤍",
        "habitat": "Mature broadleaf oak forests",
        "description": "Bold black and white plumage with unbroken white collar ring.",
        "color": "#f8fafc",
    },
    "Ficedula parva": {
        "common": "Red-breasted Flycatcher",
        "emoji": "🧡",
        "habitat": "Old-growth beech & spruce forest",
        "description": "Tiny flycatcher with Robin-like orange throat patch.",
        "color": "#fed7aa",
    },
    "Fulica atra": {
        "common": "Eurasian Coot",
        "emoji": "🪶",
        "habitat": "Open lakes, fens & park ponds",
        "description": "Slate-black waterbird with stark white bill and frontal shield.",
        "color": "#94a3b8",
    },
    "Gallinago gallinago": {
        "common": "Common Snipe",
        "emoji": "🌾",
        "habitat": "Bogs, wet meadows & marshy fens",
        "description": "Long-billed wader creating drumming sound with tail feathers.",
        "color": "#fed7aa",
    },
    "Gallinula chloropus": {
        "common": "Common Moorhen",
        "emoji": "🪶",
        "habitat": "Ponds, ditches & canal margins",
        "description": "Red-and-yellow bill with white flank stripe and bobbing head.",
        "color": "#fbcfe8",
    },
    "Gavia arctica": {
        "common": "Black-throated Loon",
        "emoji": "🌊",
        "habitat": "Deep northern boreal lakes",
        "description": "Striking geometric chequered plumage and haunting wailing cries.",
        "color": "#7dd3fc",
    },
    "Gavia stellata": {
        "common": "Red-throated Loon",
        "emoji": "🌊",
        "habitat": "Small tundra tarns & coastal bays",
        "description": "Slender uptilted bill with goose-like flight calls.",
        "color": "#7dd3fc",
    },
    "Glaucidium passerinum": {
        "common": "Eurasian Pygmy Owl",
        "emoji": "🦉",
        "habitat": "Old conifer & mixed mountain forest",
        "description": "Smallest European owl, no larger than a starling, active at dawn.",
        "color": "#c4b5fd",
    },
    "Grus grus": {
        "common": "Common Crane",
        "emoji": "🪶",
        "habitat": "Peat bogs, fens & shallow lakes",
        "description": "Tall elegant wader performing leap dances with bugling trumpets.",
        "color": "#94a3b8",
    },
    "Gyps fulvus": {
        "common": "Griffon Vulture",
        "emoji": "🦅",
        "habitat": "Gorges, mountain cliffs & open steppe",
        "description": "Huge broad-winged scavenger riding thermal updrafts over canyons.",
        "color": "#fed7aa",
    },
    "Haematopus ostralegus": {
        "common": "Eurasian Oystercatcher",
        "emoji": "🏖️",
        "habitat": "Rocky shores & sandy estuaries",
        "description": "Bold pied plumage, crimson carrot bill, and loud piping calls.",
        "color": "#fbcfe8",
    },
    "Haliaeetus albicilla": {
        "common": "White-tailed Eagle",
        "emoji": "🦅",
        "habitat": "Sea coasts, fjords & large lakes",
        "description": "Europe's largest eagle with massive broad wings.",
        "color": "#fed7aa",
    },
    "Hippolais polyglotta": {
        "common": "Melodious Warbler",
        "emoji": "🎵",
        "habitat": "Sunny scrub, hedges & open wood edges",
        "description": "Warm-climate warbler with rapid, tumbling melodic song.",
        "color": "#fef08a",
    },
    "Lagopus lagopus": {
        "common": "Willow Ptarmigan",
        "emoji": "❄️",
        "habitat": "Heather moorland & birch tundra",
        "description": "Arctic grouse turning pure snowy white in winter.",
        "color": "#f8fafc",
    },
    "Lagopus muta": {
        "common": "Rock Ptarmigan",
        "emoji": "🏔️",
        "habitat": "High alpine boulder fields & tundra",
        "description": "Hardy alpine dweller surviving extreme mountain blizzards.",
        "color": "#f8fafc",
    },
    "Lanius excubitor": {
        "common": "Great Grey Shrike",
        "emoji": "🦅",
        "habitat": "Heaths, bogs & rough pasture",
        "description": "Songbird raptor impaling prey on thorns; stark bandit mask.",
        "color": "#94a3b8",
    },
    "Larus argentatus": {
        "common": "European Herring Gull",
        "emoji": "🌊",
        "habitat": "Coasts, cliffs & seaside harbours",
        "description": "Classic large coastal gull with pale grey back and loud laughing calls.",
        "color": "#7dd3fc",
    },
    "Larus canus": {
        "common": "Mew Gull",
        "emoji": "🌊",
        "habitat": "Lakes, coasts & moorland bogs",
        "description": "Gentle-faced small gull with greenish-yellow legs.",
        "color": "#7dd3fc",
    },
    "Larus ridibundus": {
        "common": "Black-headed Gull",
        "emoji": "🌊",
        "habitat": "Inland marshes, lakes & coasts",
        "description": "Chocolate-brown summer hood and loud raucous calls in colonies.",
        "color": "#94a3b8",
    },
    "Limosa limosa": {
        "common": "Black-tailed Godwit",
        "emoji": "🌾",
        "habitat": "Wet coastal grassland & estuaries",
        "description": "Long straight bill and graceful aerial display over meadows.",
        "color": "#fed7aa",
    },
    "Linaria cannabina": {
        "common": "Common Linnet",
        "emoji": "🌸",
        "habitat": "Gorse heath, scrub & farm hedges",
        "description": "Crimson-breasted seed-eater singing melodious twittering songs.",
        "color": "#fbcfe8",
    },
    "Linaria flavirostris": {
        "common": "Twite",
        "emoji": "🌾",
        "habitat": "Upland moorland & coastal saltmarshes",
        "description": "Tough mountain finch with warm buff throat and pinkish rump.",
        "color": "#fed7aa",
    },
    "Locustella luscinioides": {
        "common": "Savi's Warbler",
        "emoji": "🎋",
        "habitat": "Dense reedbeds & fens",
        "description": "Reeling continuous mechanical song like an electric reel.",
        "color": "#86efac",
    },
    "Loxia curvirostra": {
        "common": "Red Crossbill",
        "emoji": "🌲",
        "habitat": "Conifer forests & pine plantations",
        "description": "Specialised crossed mandibles for prising conifer pine cones.",
        "color": "#fbcfe8",
    },
    "Lymnocryptes minimus": {
        "common": "Jack Snipe",
        "emoji": "🌾",
        "habitat": "Bogs & marshy tussocks",
        "description": "Secretive wader with distinctive bobbing motion when feeding.",
        "color": "#fed7aa",
    },
    "Mergus merganser": {
        "common": "Common Merganser",
        "emoji": "🦆",
        "habitat": "Clear forested rivers & lakes",
        "description": "Sleek sawbill duck diving for fish in clear mountain streams.",
        "color": "#7dd3fc",
    },
    "Mergus serrator": {
        "common": "Red-breasted Merganser",
        "emoji": "🦆",
        "habitat": "Coastal bays, fjords & estuaries",
        "description": "Shaggy double crest and slender serrated red bill.",
        "color": "#7dd3fc",
    },
    "Milvus migrans": {
        "common": "Black Kite",
        "emoji": "🦅",
        "habitat": "Rivers, lakes & open countryside",
        "description": "Abundant agile raptor with shallow-forked tail soaring over waters.",
        "color": "#fed7aa",
    },
    "Milvus milvus": {
        "common": "Red Kite",
        "emoji": "🪁",
        "habitat": "Wooded farmland & valley slopes",
        "description": "Magnificent deeply forked reddish tail and buoyant flight.",
        "color": "#fed7aa",
    },
    "Monticola saxatilis": {
        "common": "Common Rock Thrush",
        "emoji": "🏔️",
        "habitat": "Sunlit alpine scree & rocky slopes",
        "description": "Cobalt blue head and bright fiery-orange underparts.",
        "color": "#7dd3fc",
    },
    "Monticola solitarius": {
        "common": "Blue Rock Thrush",
        "emoji": "🏔️",
        "habitat": "Sea cliffs, gorges & stone ruins",
        "description": "All-dark blue plumage with clear ringing flute song.",
        "color": "#7dd3fc",
    },
    "Motacilla cinerea": {
        "common": "Grey Wagtail",
        "emoji": "💧",
        "habitat": "Fast rushing mountain streams",
        "description": "Sulphur-yellow underbelly and exceptionally long bobbing tail.",
        "color": "#fef08a",
    },
    "Nucifraga caryocatactes": {
        "common": "Spotted Nutcracker",
        "emoji": "🌲",
        "habitat": "Subalpine conifer & stone pine woods",
        "description": "Stout-billed crow caching thousands of hazel and pine nuts.",
        "color": "#fed7aa",
    },
    "Numenius arquata": {
        "common": "Eurasian Curlew",
        "emoji": "🌾",
        "habitat": "Upland moorland & coastal mudflats",
        "description": "Europe's largest wader with long downcurved bill and bubbling cry.",
        "color": "#fed7aa",
    },
    "Numenius phaeopus": {
        "common": "Whimbrel",
        "emoji": "🌾",
        "habitat": "Tundra, heaths & migration coasts",
        "description": "Striped crown pattern and rapid rippling seven-whistle call.",
        "color": "#fed7aa",
    },
    "Nycticorax nycticorax": {
        "common": "Black-crowned Night Heron",
        "emoji": "🌙",
        "habitat": "Freshwater lagoons, rivers & swamps",
        "description": "Stocky nocturnal heron with ruby-red eyes and long white nape plumes.",
        "color": "#94a3b8",
    },
    "Otus scops": {
        "common": "Eurasian Scops Owl",
        "emoji": "🦉",
        "habitat": "Mediterranean gardens, parks & olive groves",
        "description": "Tiny camouflaged owl repeating a clear single-note musical whistle.",
        "color": "#86efac",
    },
    "Pandion haliaetus": {
        "common": "Osprey",
        "emoji": "🦅",
        "habitat": "Clean lakes, coastal bays & reservoirs",
        "description": "Specialised fish-hunting raptor plunging feet-first into water.",
        "color": "#7dd3fc",
    },
    "Panurus biarmicus": {
        "common": "Bearded Reedling",
        "emoji": "🎋",
        "habitat": "Large unbroken reedbeds",
        "description": "Cinnamon-tawny reed bird with drooping black moustache and pinging calls.",
        "color": "#fed7aa",
    },
    "Perdix perdix": {
        "common": "Grey Partridge",
        "emoji": "🌾",
        "habitat": "Traditional farmland & arable stubble",
        "description": "Classic farmland covey bird with horseshoe-shaped belly patch.",
        "color": "#fed7aa",
    },
    "Periparus ater": {
        "common": "Coal Tit",
        "emoji": "🌲",
        "habitat": "Conifer plantations & gardens",
        "description": "Small tit with white nape patch foraging high in spruce needles.",
        "color": "#94a3b8",
    },
    "Pernis apivorus": {
        "common": "European Honey Buzzard",
        "emoji": "🐝",
        "habitat": "Deciduous woodland with clearings",
        "description": "Summer migrant raptor specialising in digging out wasp nests.",
        "color": "#fed7aa",
    },
    "Phalacrocorax carbo": {
        "common": "Great Cormorant",
        "emoji": "🌊",
        "habitat": "Coasts, estuaries & large inland lakes",
        "description": "Large dark waterbird perching with wings outstretched to dry.",
        "color": "#94a3b8",
    },
    "Phasianus colchicus": {
        "common": "Ring-necked Pheasant",
        "emoji": "🪶",
        "habitat": "Woodland edges & agricultural fields",
        "description": "Long-tailed colourful gamebird with explosive wing-clap and crow.",
        "color": "#fed7aa",
    },
    "Philomachus pugnax": {
        "common": "Ruff",
        "emoji": "🪶",
        "habitat": "Wet meadows & marshy shorelines",
        "description": "Spectacular varied breeding ruffs in male communal lek dances.",
        "color": "#fbcfe8",
    },
    "Phylloscopus bonelli": {
        "common": "Western Bonelli's Warbler",
        "emoji": "🌿",
        "habitat": "Dry sunny hillside oak & pine woods",
        "description": "Silvery-white underparts and clear monotonous spinning trill.",
        "color": "#86efac",
    },
    "Phylloscopus inornatus": {
        "common": "Yellow-browed Warbler",
        "emoji": "🍃",
        "habitat": "Taiga birch scrub & coastal bushes",
        "description": "Hyperactive eastern migrant with prominent double wingbars.",
        "color": "#fef08a",
    },
    "Phylloscopus sibilatrix": {
        "common": "Wood Warbler",
        "emoji": "🍃",
        "habitat": "Mature beech & oak closed canopy",
        "description": "Bright lemon-yellow throat with accelerating spinning-coin song.",
        "color": "#fef08a",
    },
    "Pica pica": {
        "common": "Eurasian Magpie",
        "emoji": "🪶",
        "habitat": "Farmland, parks, gardens & scrub",
        "description": "Clever, inquisitive corvid with long iridescent metallic tail.",
        "color": "#7dd3fc",
    },
    "Picoides tridactylus": {
        "common": "Eurasian Three-toed Woodpecker",
        "emoji": "🪵",
        "habitat": "Old boreal taiga & dead spruce trees",
        "description": "Northern woodpecker with yellow crown and three toes.",
        "color": "#fef08a",
    },
    "Picus canus": {
        "common": "Grey-headed Woodpecker",
        "emoji": "🪵",
        "habitat": "Deciduous river valleys & hills",
        "description": "Grey neck with scarlet crown patch and descending piping call.",
        "color": "#86efac",
    },
    "Platalea leucorodia": {
        "common": "Eurasian Spoonbill",
        "emoji": "🪶",
        "habitat": "Shallow fens, lagoons & coastal flats",
        "description": "Pure white plumage with remarkable spatula-shaped foraging bill.",
        "color": "#f8fafc",
    },
    "Plectrophenax nivalis": {
        "common": "Snow Bunting",
        "emoji": "❄️",
        "habitat": "High mountain tops & arctic tundra",
        "description": "Snowflake bird flourishing on frozen arctic windswept ridges.",
        "color": "#f8fafc",
    },
    "Pluvialis apricaria": {
        "common": "European Golden Plover",
        "emoji": "✨",
        "habitat": "Upland peat moorland & winter fields",
        "description": "Spangled golden back with haunting melancholic piping whistle.",
        "color": "#fef08a",
    },
    "Pluvialis squatarola": {
        "common": "Grey Plover",
        "emoji": "🌊",
        "habitat": "Tide-swept coastal mudflats & beaches",
        "description": "Silver-chequered shorebird with prominent black armpit patches.",
        "color": "#94a3b8",
    },
    "Podiceps cristatus": {
        "common": "Great Crested Grebe",
        "emoji": "🪶",
        "habitat": "Large freshwater lakes & reservoirs",
        "description": "Spectacular head-shaking courtship weed dances on open waters.",
        "color": "#fbcfe8",
    },
    "Porzana porzana": {
        "common": "Spotted Crake",
        "emoji": "🎋",
        "habitat": "Dense swampy vegetation & flooded fens",
        "description": "Nocturnal whiplash call echoing across flooded fens.",
        "color": "#fed7aa",
    },
    "Prunella modularis": {
        "common": "Dunnock",
        "emoji": "🍂",
        "habitat": "Garden hedges, scrub & woodland edge",
        "description": "Unassuming hedge bird with fine warbler bill and rapid warble.",
        "color": "#94a3b8",
    },
    "Pyrrhocorax graculus": {
        "common": "Alpine Chough",
        "emoji": "🏔️",
        "habitat": "High alpine peaks & ski crags",
        "description": "Yellow-billed acrobat gliding along cliff faces in mountain gales.",
        "color": "#fef08a",
    },
    "Pyrrhocorax pyrrhocorax": {
        "common": "Red-billed Chough",
        "emoji": "🏔️",
        "habitat": "Sea cliffs & mountain pastures",
        "description": "Curved coral-red bill with buoyant aerial loops and ringing cry.",
        "color": "#fbcfe8",
    },
    "Pyrrhula pyrrhula": {
        "common": "Eurasian Bullfinch",
        "emoji": "🍓",
        "habitat": "Dense woodland, orchard buds & scrub",
        "description": "Glowing rose-red breast and soft melancholic piping whistle.",
        "color": "#fbcfe8",
    },
    "Rallus aquaticus": {
        "common": "Water Rail",
        "emoji": "🎋",
        "habitat": "Dense wetlands, reedbeds & marshes",
        "description": "Secretive wader with long red bill and bizarre piglet-like squeals.",
        "color": "#fbcfe8",
    },
    "Recurvirostra avosetta": {
        "common": "Pied Avocet",
        "emoji": "🏖️",
        "habitat": "Coastal brackish lagoons & fens",
        "description": "Striking upturned bill sweeping sideways through shallow water.",
        "color": "#7dd3fc",
    },
    "Remiz pendulinus": {
        "common": "Eurasian Penduline Tit",
        "emoji": "🪺",
        "habitat": "Willows & reeds along lake shores",
        "description": "Master builder of intricate hanging pouch nests from willow down.",
        "color": "#fed7aa",
    },
    "Riparia riparia": {
        "common": "Sand Martin",
        "emoji": "🏖️",
        "habitat": "Sandy riverbanks & gravel quarry cliffs",
        "description": "Tiny agile brown-backed swallow nesting in colonial sand burrows.",
        "color": "#fed7aa",
    },
    "Scolopax rusticola": {
        "common": "Eurasian Woodcock",
        "emoji": "🍂",
        "habitat": "Damp deciduous & mixed forest floor",
        "description": "Nocturnal roding display flight at dusk with croaking grunt calls.",
        "color": "#fed7aa",
    },
    "Serinus serinus": {
        "common": "European Serin",
        "emoji": "🌻",
        "habitat": "Sunny parkland, vineyards & gardens",
        "description": "Tiny bright yellow finch with sizzling, rapid song like crushed glass.",
        "color": "#fef08a",
    },
    "Somateria mollissima": {
        "common": "Common Eider",
        "emoji": "🌊",
        "habitat": "Rocky sea coasts & coastal skerries",
        "description": "Heavy sea duck producing soft coos on ocean swells.",
        "color": "#7dd3fc",
    },
    "Sterna hirundo": {
        "common": "Common Tern",
        "emoji": "🌊",
        "habitat": "Coastal islands, shingle beaches & lakes",
        "description": "Graceful sea swallow with forked streamers plunging for minnows.",
        "color": "#7dd3fc",
    },
    "Streptopelia turtur": {
        "common": "European Turtle Dove",
        "emoji": "🕊️",
        "habitat": "Sunny woodland edge & farm hedgerows",
        "description": "Gentle purring turr-turr song of summer woodland borders.",
        "color": "#fbcfe8",
    },
    "Strix aluco": {
        "common": "Tawny Owl",
        "emoji": "🦉",
        "habitat": "Deciduous woods, parkland & farm groves",
        "description": "Classic hooting owl of European nights.",
        "color": "#fed7aa",
    },
    "Strix uralensis": {
        "common": "Ural Owl",
        "emoji": "🦉",
        "habitat": "Old-growth taiga & mixed boreal woods",
        "description": "Large, pale grey forest owl with long tail and fierce nest defense.",
        "color": "#94a3b8",
    },
    "Sylvia melanocephala": {
        "common": "Sardinian Warbler",
        "emoji": "🌿",
        "habitat": "Mediterranean maquis & coastal scrub",
        "description": "Velvet-black hood with fiery red eye-ring and churring alarm rattle.",
        "color": "#fbcfe8",
    },
    "Sylvia undata": {
        "common": "Dartford Warbler",
        "emoji": "🪻",
        "habitat": "Lowland heather heath & gorse commons",
        "description": "Dark wine-red underparts with long cocked tail in dense gorse.",
        "color": "#c4b5fd",
    },
    "Tachybaptus ruficollis": {
        "common": "Little Grebe",
        "emoji": "💧",
        "habitat": "Vegetated ponds, quiet oxbows & ditches",
        "description": "Tiny dabchick diving with rapid bubbling whinnying trill.",
        "color": "#86efac",
    },
    "Tadorna tadorna": {
        "common": "Common Shelduck",
        "emoji": "🦆",
        "habitat": "Estuaries, mudflats & sandy coasts",
        "description": "Goose-like coastal duck with chestnut chest band and red bill knob.",
        "color": "#fed7aa",
    },
    "Tetrao urogallus": {
        "common": "Western Capercaillie",
        "emoji": "🌲",
        "habitat": "Ancient Caledonian & taiga pine forest",
        "description": "Giant woodland grouse performing clicking and cork-popping lek song.",
        "color": "#7dd3fc",
    },
    "Tichodroma muraria": {
        "common": "Wallcreeper",
        "emoji": "🦋",
        "habitat": "Vertical alpine limestone cliff faces",
        "description": "Crimson-winged butterfly-like bird hopping up sheer precipices.",
        "color": "#fbcfe8",
    },
    "Tringa glareola": {
        "common": "Wood Sandpiper",
        "emoji": "🌿",
        "habitat": "Taiga bogs & marshy pool margins",
        "description": "Spotted wader performing high yodelling song flights over muskeg.",
        "color": "#86efac",
    },
    "Tringa totanus": {
        "common": "Common Redshank",
        "emoji": "🏖️",
        "habitat": "Saltmarshes, wet coastal meadows & fens",
        "description": "Sentinel of the marsh with bright orange-red legs and ringing alarm.",
        "color": "#fed7aa",
    },
    "Turdus iliacus": {
        "common": "Redwing",
        "emoji": "🍂",
        "habitat": "Birch woods & winter berry hedges",
        "description": "Winter thrush with bold creamy eyestripe and rusty flank patches.",
        "color": "#fbcfe8",
    },
    "Turdus pilaris": {
        "common": "Fieldfare",
        "emoji": "🍁",
        "habitat": "Open birch woodland & orchards",
        "description": "Handsome blue-grey capped thrush calling with chattering notes.",
        "color": "#94a3b8",
    },
    "Turdus torquatus": {
        "common": "Ring Ouzel",
        "emoji": "🏔️",
        "habitat": "Rocky heather slopes & alpine gullies",
        "description": "Mountain blackbird sporting a crisp white crescent breast gorget.",
        "color": "#94a3b8",
    },
    "Tyto alba": {
        "common": "Western Barn Owl",
        "emoji": "🤍",
        "habitat": "Farmland, barns & rough grass margins",
        "description": "Silent ghostly hunter with heart-shaped white face and rasping shriek.",
        "color": "#f8fafc",
    },
    "Vanellus vanellus": {
        "common": "Northern Lapwing",
        "emoji": "🌾",
        "habitat": "Pastures, arable wetlands & moorland",
        "description": "Iridescent green plumage, slender upcurved crest, and peewit cry.",
        "color": "#7dd3fc",
    },
}

def main():
    full_db = dict(_SPECIES_DB)
    full_db.update(additional)

    all_species_sorted = sorted(full_db.keys())[:182]
    print(f"Total compiled species: {len(all_species_sorted)}")

    idx2label = {str(i): sp for i, sp in enumerate(all_species_sorted)}
    label2idx = {sp: i for i, sp in enumerate(all_species_sorted)}

    label_map_obj = {
        "label2idx": label2idx,
        "idx2label": idx2label,
    }

    ckpt_dir = os.path.join(ROOT, "models", "checkpoints")
    os.makedirs(ckpt_dir, exist_ok=True)
    out_path = os.path.join(ckpt_dir, "label_map.json")

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(label_map_obj, f, indent=2, ensure_ascii=False)

    print(f"Generated: {out_path} ({len(idx2label)} classes)")

    # Update species_names.py
    species_file = os.path.join(SRC, "inference", "species_names.py")
    header = '"""\nOrnitho-Ex | Species Name and Info Registry\n\nMaps numeric class indices (0-181) to species information.\n"""\n\nfrom __future__ import annotations\nimport json\nfrom pathlib import Path\n\n_SPECIES_DB: dict[str, dict] = '
    footer = '''\n\ndef _build_fallback_index_map() -> dict[int, dict]:\n    all_sci = sorted(_SPECIES_DB.keys())\n    return {i: {"scientific": sp, **_SPECIES_DB[sp]} for i, sp in enumerate(all_sci)}\n\ndef load_label_map(label_map_path: str | None = None) -> dict[int, dict]:\n    if label_map_path:\n        p = Path(label_map_path)\n        if p.exists():\n            with open(p, encoding="utf-8") as f:\n                raw = json.load(f)\n            idx2label = raw.get("idx2label", {})\n            result = {}\n            for idx_str, sci_name in idx2label.items():\n                idx = int(idx_str)\n                info = _SPECIES_DB.get(sci_name, {})\n                result[idx] = {\n                    "scientific":   sci_name,\n                    "common":       info.get("common",      sci_name),\n                    "emoji":        info.get("emoji",       "🐦"),\n                    "habitat":      info.get("habitat",     "Temperate Habitats"),\n                    "description":  info.get("description", "Identified avian species."),\n                    "color":        info.get("color",       "#7dd3fc"),\n                }\n            return result\n    return _build_fallback_index_map()\n\ndef get_species_info(idx: int, label_map: dict) -> dict:\n    return label_map.get(idx, {\n        "scientific":  f"Avian Species #{idx}",\n        "common":      f"Species #{idx}",\n        "emoji":       "🐦",\n        "habitat":     "Temperate Habitats",\n        "description": f"Model identified vocalisation patterns for class {idx}.",\n        "color":       "#7dd3fc",\n    })\n'''
    
    with open(species_file, "w", encoding="utf-8") as f:
        f.write(header + json.dumps(full_db, indent=4, ensure_ascii=False) + footer)
    print("Updated species_names.py successfully!")

if __name__ == "__main__":
    main()
